### ISSUE TITLE
1.9.5 new Toggle Colors

### ISSUE THREAD

**Issue by jtrack3d** [jothepro/doxygen-awesome-css#87] opened 2022-09-08 17:46 UTC
With 1.9.5 there are new classes and colors to not alternate dark/light correctly anymore.

Class lists, tree view and main page colors.

This is in addition to the scroll bar mentioned before.

**Comment by dsieger** [comment] 2022-09-12 10:28
Adding

```css
table.directory tr.odd {
  background-color: inherit;
}
```

fixes the alternating color issue in class lists etc.

No idea about the scrollbars, there seem to be two different issues.

1. Light blue background color in the nav tree:
  
  ![image](https://user-images.githubusercontent.com/6951585/189631325-35225024-df8c-4892-9129-c5a606214e94.png)

2. Blue scrollbar handle (right) in the main content area:
  
  ![image](https://user-images.githubusercontent.com/6951585/189631512-46fa7af0-73b1-44bd-a995-40f0b98b2e4d.png)

**Comment by dsieger** [comment] 2022-09-13 20:25
Thanks @jothepro 🙏

**Comment by jothepro** [comment] 2022-09-20 15:46
Closing this, I think the issue is resolved.

**Closed by jothepro** 2022-09-20 15:46 UTC
