### ISSUE TITLE
Fragment copy button not available when serving the HTML on remote server

### ISSUE THREAD

**Issue by zeroxia** [jothepro/doxygen-awesome-css#125] opened 2023-07-28 06:30 UTC
Hi,

I enabled the fragment copy extension in the Doxygen.

When viewing it as `http://127.0.0.1:8080/`, the code copy works OK.

When I put the HTML to a remote HTTP server, and view it like `http://30.88.88.88`, then the copy button is not available.

How to fix this?

Thanks.

**Comment by zeroxia** [comment] 2023-07-28 06:37
I found on stackoverflow there is a question might be related:

https://stackoverflow.com/questions/72237719/not-being-able-to-copy-url-to-clipboard-without-adding-the-protocol-https

> this is due to not using HTTPS. According to MDN [Clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) docs: "This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)". The best option would be to just use HTTPS.

Is there any workaround? I'm only sharing the documentation within company LAN, setting up HTTPS seems overkill.

**Comment by jothepro** [comment] 2023-07-28 12:24
As you already stated correctly, this is a restriction enforced by the browser. As a user of the API one has no influence on this. So I don't think there is a workaround other than serving the documentation over https.

**Comment by jothepro** [comment] 2023-10-06 13:33
Closing this issue because this is not a bug, but rather a restriction enforced by browsers.

**Closed by jothepro** 2023-10-06 13:33 UTC
Labels: question
