### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by tim-gromeyer** [jothepro/doxygen-awesome-css#107] opened 2023-01-19 14:14 UTC
Currently if I click something on the TOC it jumps to the section. Yesterday I saw a video on YouTube about how to implement smooth scrolling. IMO smooth scrolling should be the default behavior. Here's the link to the Video: https://youtube.com/shorts/hk3RgcBx5Fc?feature=share

**Comment by jothepro** [comment] 2023-02-13 19:27
Yes, that would be nice to have! The problem is that doxygen itself seems to do some nasty jQuery stuff to add smooth scrolling when clicking on items in the navigation tree.
I think I've tried adding smooth scrolling before but it was really glitchy due to Javascript messing with the scrolling at the same time. :/
If you can make it work somehow pls let me know! :)

**Comment by tim-gromeyer** [comment] 2023-02-13 20:31
I created a issue, see doxygen/doxygen#9855

**Comment by tim-gromeyer** [comment] 2023-02-14 20:00
They fixed it. Should I close the issue or leave it open til the release of doxygen v1.9.7?

**Comment by jothepro** [comment] 2023-02-15 07:48
Awesome! I'll close this issue then. Looking forward to Doxygen 1.9.7! 👍

**Closed by jothepro** 2023-02-15 07:48 UTC
Labels: enhancement
